//
// ========================================================================
// Copyright (c) 1995 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[dump]]
= Jetty Component Dump

The Jetty Server Dump is a useful tool for debugging the state of the server.
See the xref:programming-guide:troubleshooting/component-dump.adoc[Jetty Server Dump] section for detailed information.

[[dump-start-stop]]
== Dump at Server Start/Stop

The dump operation may also be invoked just after the `Server` starts (to log the state of the freshly started server), and just before the `Server` stops (which may be useful to log the state of server that is not working properly).

Standalone Jetty uses two properties to control this behaviour which are referenced in `jetty.xml` to call these setters.
These properties are `jetty.server.dumpAfterStart` and `jetty.server.dumpBeforeStop`.

These can be temporarily enabled by supplying these properties as command line arguments,
or to make this change persistent across server restarts they can be enabled via the `server.ini` file (see xref:operations-guide:modules/standard.adoc#server-config[Server Configuration]).

[source,subs=+quotes]
----
$ java -jar $JETTY_HOME/start.jar *jetty.server.dumpAfterStart=true*
----
